### ISSUE TITLE
Use BB provided libraries

### ISSUE THREAD

**Issue by ViralBShah** [abhinavmehndiratta/SuiteSparseGraphBLAS.jl#9]
Once https://github.com/JuliaPackaging/Yggdrasil/pull/336 is merged, it would be nice to update this package to use the BB built libraries.

**Comment by abhinavmehndiratta** [comment]
I'll update the package once it is merged, thank you for the effort !

**Comment by abhinavmehndiratta** [comment]
Okay https://github.com/JuliaPackaging/Yggdrasil/pull/336 is merged, could you help me incorporate it here ?

**Comment by ViralBShah** [comment]
Just need to add the jll into Project.toml. example: https://github.com/JuliaSparse/Metis.jl/blob/master/Project.toml

Make sure the jll is published in the JuliaBinaryWrappers org.

Remove the deps folder. Then tag a new release.

**Comment by ViralBShah** [comment]
@giordano do we document these steps somewhere?

**Comment by giordano** [comment]
There is a section in the [`README.md`](https://github.com/JuliaPackaging/Yggdrasil/blob/1daabfd766cce355a3865bd5a213e2c669b9ab86/README.md#jll-packages) of Yggdrasil with links to relevant PRs

**Comment by abhinavmehndiratta** [comment]
Thank you for working on this ! Resolved by #12, closing the issue now.
